# Generated by Django 6.0.4 on 2026-04-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=9, null=True, unique=True, verbose_name='Telefon raqami'),
        ),
    ]
