# Generated by Django 6.0.4 on 2026-05-05 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Foydalanuvchini tuliq ismi'),
            preserve_default=False,
        ),
    ]
