# Generated by Django 6.0.4 on 2026-04-25 05:22

import apps.messages_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_groupstudent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Xabar matni')),
                ('attachment', models.FileField(blank=True, null=True, upload_to=apps.messages_app.models.message_file_upload_path, verbose_name='Fayl')),
                ('image', models.ImageField(blank=True, null=True, upload_to=apps.messages_app.models.message_image_upload_path, verbose_name='Rasm')),
                ('message_type', models.CharField(choices=[('text', 'Matn'), ('file', 'Fayl'), ('image', 'Rasm')], default='text', max_length=10, verbose_name='Xabar turi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.group', verbose_name='Guruh')),
                ('read_by', models.ManyToManyField(blank=True, related_name='read_group_messages', to=settings.AUTH_USER_MODEL, verbose_name="O'qiganlar")),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_group_messages', to=settings.AUTH_USER_MODEL, verbose_name='Yuboruvchi')),
            ],
            options={
                'verbose_name': 'Guruh xabari',
                'verbose_name_plural': 'Guruh xabarlari',
                'ordering': ['created_at'],
            },
        ),
    ]
