# Generated by Django 6.0.4 on 2026-04-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kurs nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('category', models.CharField(max_length=100, verbose_name='Kategoriya')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=15, verbose_name='Daraja')),
                ('duration_months', models.PositiveIntegerField(default=3, verbose_name='Davomiyligi (oy)')),
                ('price', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Narxi')),
                ('image', models.CharField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
