# Generated by Django 6.0.4 on 2026-04-23 05:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
        migrations.AddField(
            model_name='course',
            name='couser_objective',
            field=models.CharField(choices=[('ielts', 'IELTS'), ('toefl', 'TOEFL'), ('general', 'General English'), ('kids', 'Bolalar uchun'), ('business', 'Business English')], default=django.utils.timezone.now, max_length=100, verbose_name='Kursni maqasadi'),
            preserve_default=False,
        ),
    ]
