# Generated by Django 6.0.4 on 2026-04-23 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Guruh nomi')),
                ('start_time', models.TimeField(verbose_name='Dars boshlanishi')),
                ('end_time', models.TimeField(verbose_name='Dars tugashi')),
                ('week_days', models.JSONField(default=list, verbose_name='Hafta kunlari')),
                ('status', models.CharField(choices=[('active', 'Faol'), ('inactive', 'Faolsiz'), ('finished', 'Yakunlangan')], default='active', max_length=10)),
                ('start_date', models.DateField(verbose_name='Boshlanish sanasi')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Tugash sanasi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='courses.course', verbose_name='Kurs')),
                ('teacher', models.ForeignKey(limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups_teacher', to=settings.AUTH_USER_MODEL, verbose_name='Ustoz')),
            ],
        ),
    ]
