# Generated by Django 6.0.4 on 2026-04-21 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', 'Beginner'), ('elementary', 'Elementary'), ('pre_intermediate', 'Pre-Intermediate'), ('intermediate', 'Intermediate'), ('upper_Intermediate', 'Upper-Intermediate'), ('advanced', 'Advanced'), ('proficiency', 'Proficiency')], default='beginner', max_length=30, verbose_name='Daraja')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Tajriba (yil)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holati')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
        ),
    ]
